# SPDX-FileCopyrightText: 2026 AlitaBernachot
#
# SPDX-License-Identifier: MIT

"""
LangGraph state schemas for the V2 multi-agent backend.

Two state types are defined:

SubAgentState
    Used by each agent's compiled subgraph (a single execute_node).
    Keys shared with OrchestratorState (``query``, ``session_id``,
    ``context``, ``sub_results``) are mapped in automatically by LangGraph
    when the subgraph is invoked as a node.  After the subgraph completes,
    only the shared keys are merged back into the parent state.

OrchestratorState
    Used by the main orchestrator StateGraph.
    ``sub_results`` uses a ``_merge_dicts`` reducer so that parallel
    sub-agent results are accumulated rather than overwritten.
"""
from __future__ import annotations

from typing import Annotated, Any

from typing_extensions import TypedDict


def _merge_dicts(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    """Reducer: merge two dicts (right wins on conflicts)."""
    return {**left, **right}


def _keep_last(left: Any, right: Any) -> Any:
    """Reducer: keep the most recent value (used for keys written by parallel subgraphs)."""
    return right


class SubAgentState(TypedDict):
    """State for each sub-agent subgraph.

    Shared keys (query, session_id, context, sub_results) come from the
    parent OrchestratorState.  The subgraph consists of a single
    execute_node that calls ``agent.run()`` and writes the result to
    ``sub_results``, which is then merged back into the parent state.
    """

    # ── shared with OrchestratorState (passed in by LangGraph) ───────────────
    query: str
    session_id: str
    context: dict[str, Any]
    # ── shared output key (merged back into parent via _merge_dicts) ─────────
    sub_results: Annotated[dict[str, Any], _merge_dicts]


class OrchestratorState(TypedDict):
    """Shared state threaded through the orchestrator graph.

    Topology:
        memory_node → ambiguity_node → [hitl_wait_node?] → router_node
            → [Send fan-out] → <agent subgraphs> → merge_node → END
    """

    # ── core request ──────────────────────────────────────────────────────────
    # Annotated with _keep_last so that parallel sub-agent subgraphs (fan-out
    # via Send) can each write these shared keys back without raising
    # InvalidUpdateError.  The value never actually changes during fan-out —
    # the reducer just allows concurrent writes.
    query: Annotated[str, _keep_last]
    session_id: Annotated[str, _keep_last]
    context: Annotated[dict[str, Any], _keep_last]

    # ── routing ───────────────────────────────────────────────────────────────
    selected_sources: Annotated[list[str], _keep_last]
    agents_to_call: list[str]
    execution_reasoning: str

    # ── sub-agent results (fan-out via Send, merged by _merge_dicts) ─────────
    sub_results: Annotated[dict[str, Any], _merge_dicts]

    # ── final output ──────────────────────────────────────────────────────────
    final_answer: str
    confidence: float

    # ── Session title (generated by title_node from the first query) ──────────
    session_title: str

    # ── HITL ──────────────────────────────────────────────────────────────────
    hitl_request_id: str
    hitl_questions: list[str]
    hitl_status: str  # "" | "pending" | "resolved" | "timeout"

    # ── Agent choice (structured disambiguation, reusable) ────────────────────
    choice_request_id: str
    choice_agent: str   # which agent issued the choice request
    choice_status: str  # "" | "pending" | "resolved" | "timeout"
    choice_query: str   # rewritten query after choice is resolved

    # ── Post-processing output (humanoutput / dataviz / mapviz nodes) ─────────
    output_decision: dict[str, Any]   # {"needs_map": bool, "needs_dataviz": bool}
    dataviz: dict[str, Any]           # chart / KPI / table payload for frontend
    geojson: dict[str, Any]           # GeoJSON FeatureCollection for frontend
