---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	merge(merge)
	post_process_router(post_process_router)
	mapviz_agent(mapviz_agent)
	dataviz_agent(dataviz_agent)
	humanoutput_agent(humanoutput_agent)
	neo4j_agent(neo4j_agent)
	rdf_agent(rdf_agent)
	vector_agent(vector_agent)
	postgis_agent(postgis_agent)
	data_gouv_agent(data_gouv_agent)
	geo_agent(geo_agent)
	smart_dispatcher(smart_dispatcher)
	intent_parser(intent_parser)
	__end__([<p>__end__</p>]):::last
	__start__ --> intent_parser;
	data_gouv_agent --> post_process_router;
	dataviz_agent --> merge;
	geo_agent --> post_process_router;
	humanoutput_agent -.-> dataviz_agent;
	humanoutput_agent -.-> mapviz_agent;
	humanoutput_agent -.-> merge;
	intent_parser --> smart_dispatcher;
	mapviz_agent --> merge;
	neo4j_agent --> post_process_router;
	post_process_router --> humanoutput_agent;
	postgis_agent --> post_process_router;
	rdf_agent --> post_process_router;
	smart_dispatcher -.-> data_gouv_agent;
	smart_dispatcher -.-> geo_agent;
	smart_dispatcher -.-> merge;
	smart_dispatcher -.-> neo4j_agent;
	smart_dispatcher -.-> post_process_router;
	smart_dispatcher -.-> postgis_agent;
	smart_dispatcher -.-> rdf_agent;
	smart_dispatcher -.-> vector_agent;
	vector_agent --> post_process_router;
	merge --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
